---
title: Welcome to STA 101
subtitle: Lecture 1
format: revealjs
auto-stretch: false
---

# Course Details

## Teaching team {.smaller}

::: columns
::: {.column width="50%"}
### Instructor

Kat Husat

Old Chem 406

[kat.husar\@duke.edu](mailto:kat.husar@duke.edu)
:::

::: {.column width="50%"}
### Teaching assistant

John Gillen

[john.gillen\@duke.edu](mailto:john.gillen@duke.edu)
:::
:::

## Timetable

-   Lectures at Perk LINK 087 (Classroom 3): Mon - Fri 11:00 - 12:15 pm
-   Labs at Perkins LINK 087 (Classroom 3): Mon + Thu 9:30 - 10:45 am

## Learning objectives {.smaller}

1.  Recognize the importance of data collection, identify limitations in data collection methods, and determine how they affect the scope of inference.

2.  Use statistical software to summarize data numerically and visually, and to perform data analysis.

3.  Have a conceptual understanding of the unified nature of statistical inference.

4.  Apply estimation and testing methods to analyze single variables or the relationship between two variables in order to understand natural phenomena and make data-based decisions.

5.  Model numerical response variables using a single or multiple explanatory variables.

6.  Interpret results correctly, effectively, and in context without relying on statistical jargon.

7.  Critique data-based claims and evaluate data-based decisions.

8.  Complete research projects demonstrating mastery of statistical data analysis from exploratory analysis to inference to modeling.

# Course components

## Course website

::: {.large style="text-align: center;"}
[sta101-su2024.github.io](https://sta101-su2024.github.io/)
:::

::: {.hand-pink style="text-align: center;"}
aka "the one link to rule them all"
:::

::: {style="text-align: center;"}
```{=html}
<iframe width="1000" height="400" src="https://sta101-su2024.github.io/" frameborder="1" style="background:white;"></iframe>
```
:::

## Lectures

-   In person

-   Attendance is required (as long as you're healthy!)

-   A little bit of everything:

    -   Traditional lecture
    -   Live coding + demos
    -   Short exercises + solution discussion

## Labs

-   Attendance is required (as long as you're healthy!)

-   Opportunity to work on course assignments

-   Opportunity to work on a project

## Announcements

-   Posted on Canvas (Announcements) and sent via email, be sure to check both regularly

-   I'll assume that you've read an announcement by the next "business" day

## Diversity and inclusion {.smaller}

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit.

-   If you have a name that differs from those that appear in your official Duke records, please let me know! Add your name pronunciation to your Canvas and Slack profiles.

-   Please let me know your preferred pronouns and add these to your Canvas and Slack profiles.

-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. If you prefer to speak with someone outside of the course, your advisers and deans are excellent resources.

-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it.

## Accessibility

-   The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments.

-   We will have **in class exams**. If you need special accommodations, please book the **testing center** ASAP!

-   I am committed to making all course materials accessible and I'm always learning how to do this better. If any course component is not accessible to you in any way, please don't hesitate to let me know.

# Assessments

## Attendance + participation (5%)

-   Required throughout the semester in lecture and lab

-   Students who attend at least 80% of the lectures and participate regularly in lecture and/or other course venues (discussion board) will receive full credit for the lecture attendance

-   You are allowed to miss 2 lab meetings without penalty.

-   Lecture and lab attendance will be equally weighted in the final attendace grade calculation.

::: callout-tip
If you attend at least 80% of the lectures and miss at most 2 lab meetings, you'll get all available points for this component.
:::

## Labs (35%)

-   Submitted on Gradescope, individual, can discuss with classmates
-   Lab sessions allocated to working on assignments
-   Due by 11:59 pm ET on the indicated day on the course schedule

::: callout-tip
Lowest lab score is dropped, whether it's an actual low score or a 0 from not turning it in.
:::

## Exam {.smaller}

-   One exams, each 30%

-   The exam comprised of two parts:

    -   In class: 75 minute in-class exam. Closed book, one sheet of notes ("cheat sheet", no larger than 8 1/2 x 11, both sides, **must be prepared by you**) -- 70% of the grade

    -   Take home: 48 hours to complete the take home portion. The take home portion will follow from the in class exam and focus on the analysis of a dataset introduced in the take home exam -- 30% of the grade

::: callout-caution
Exam dates cannot be changed and no make-up exams will be given. If you can't take the exams on these dates, you should drop this class.
:::

## Project {.smaller}

-   Project (30%)
    -   Dataset of your choice, method of your choice
    -   Presentation and write-up
    -   Presentations on the lass class date
-   Interim deadlines
-   Some lab sessions allocated to working on projects and getting feedback from the instructor

::: callout-caution
Final presentation date cannot be changed. If you can't present on that date, you should drop this class.
:::

# Course policies

## Late work policy {.smaller}

-   Labs:

    -   Late, but within 24 hours of deadline: -20% of available points

    -   Any later: No credit, and we will not provide written feedback

    -   Note that lowest lab score will be dropped, even if that score is a 0

-   Project submissions:

    -   Proposal late, but within 24 hours of deadline: -20% of available points
    -   Any later: No credit, and we will not provide written feedback

-   Project presentation: Late submissions not accepted

::: callout-caution
No late submissions on the final report.
:::

## Collaboration policy

-   Exams must be completed individually, you may not discuss answers with teammates, clarification questions should only be asked to myself and the TAs

-   Labs must be completed individually. You may not directly share answers / code with others, however you are welcome to discuss the problems in general and ask for advice

## Sharing / reusing code policy

-   We are aware that a huge volume of code is available on the web, and many tasks may have solutions posted

-   Unless explicitly stated otherwise, this course's policy is that you may make use of any online resources (e.g., StackOverflow) but you must explicitly cite where you obtained any code you directly use or use as inspiration in your solution(s)

-   Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism, regardless of source

## Generative AI policy {.smaller}

You should treat generative AI, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:[^1]

[^1]: These guiding principles are based on [*Course Policies related to ChatGPT and other AI Tools*](https://docs.google.com/document/d/1WpCeTyiWCPQ9MNCsFeKMDQLSTsg1oKfNIH6MzoSFXqQ/preview) developed by Joel Gladd, Ph.D.

\(1\) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning.

\(2\) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

-   **✅ AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **❌ AI tools for narrative:** Unless instructed otherwise, you may not use generative AI to write narrative on assignments. In general, you may use generative AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.

## Academic integrity

To uphold the Duke Community Standard:

> -   I will not lie, cheat, or steal in my academic endeavors;
> -   I will conduct myself honorably in all my endeavors; and
> -   I will act if the Standard is compromised.

<br><br>

::: {.large .hand-pink style="text-align: center"}
most importantly:

ask if you're not sure if something violates a policy!
:::

# Support

## Wellness

I want to make sure that you learn everything you were hoping to learn from this class. If this requires flexibility, please don't hesitate to ask.

-   You never owe me personal information about your health (mental or physical) but you're always welcome to talk to me. If I can't help, I likely know someone who can.

-   I want you to learn lots of things from this class, but I primarily want you to stay healthy, balanced, and grounded.

# Course Tools

## RStudio

::: {.large style="text-align: center;"}
<https://cmgr.oit.duke.edu/containers>
:::

-   Requires internet connection to access

-   Provides consistency in hardware and software environments

-   Local R installations are fine but we will not guarantee support

## Discussion Board {.smaller}

-   On Canvas

-   Ask **and answer** questions related to course logistics, assignment, etc. here

-   Personal questions (e.g., extensions, illnesses, etc.) should be via email to me

# To do before...

## To do before... {.smaller}

### the next class tomorrow

-   Read the [syllabus](https://sta101-su2024.github.io/course-syllabus.html)

-   Complete the *Getting to know you* survey

-   Complete the readings

# Hello data

## Application exercise: UN Votes

::: task
Go to Container and upload the document titled `unvotes.qmd`. Review the narrative and the data visualization you just created. Then, change "Turkey" to another country of your choice. Re-render the document. Show the plot you created to your neighbor and discuss (1) why you chose that country and (2) how this new visualization is different than the original (and what that says about country politics, if anything).

Time permitting: How were these data collected?
:::
