---
title: "Lab 9 - Wrap it up!"
---

By the end of this lab you will

-   calculate probabilities under the normal distribution

-   construct and interpret confidence intervals via bootstrapping

For all visualizations you create, be sure to include informative titles for the plot, axes, and legend!

# Getting started

1.  Go to [Duke Container Manager](https://cmgr.oit.duke.edu/containers) and create a new folder titled *lab-9*.

2.  Download the files from [Canvas](https://canvas.duke.edu/courses/32831/pages/thu-jun-19-inference-for-two-independent-means) and upload them into the new folder you created in step 1.

3.  Complete the exercises in this document.

# Packages

We'll use the following packages in this lab:

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(tidymodels)
library(dsbox)
```

# Part 1: Second chances

## Exercise 1

A second chance for an exercise: Take one of the exercises from a previous lab assignment, ideally one you received more feedback on / lost more points on and improve it. First, write one sentence reminding us of the specific exercise and a a few sentences on why you chose this specific exercise to improve and how you plan to improve it. Some of these improvements might be "fixes" for things that were pointed out as missing or incorrect. Some of them might be things you hoped to do before the homework deadline, but didn't get a chance to. Some notes for completing this exercise:

-   You will need to add your data from your the homework assignment to the folder in this assignment. You do not need to also add a data dictionary.

-   You will need to copy over any code needed for cleaning / preparing your data for this specific exercise. You can reuse code from your previous assignment but note that we will re-evaluate your code as part of the grading for this exercise. This means we might catch something wrong with it that we didn't catch before, so if you spot any errors make sure to fix them.

-   Don't worry about being critical of your own work. Even if you lost no points on the plot, if you think it can be improved, articulate how / why. We will not go back and penalize for any mistakes you might point out that we didn't catch at the time of grading your homework assignment. There's no risk to being critical!

# Part 2: IMS exercises

## Exercise 2

::: exercise
IMS - [Chapter 19 exercises](https://openintro-ims2.netlify.app/19-inference-one-mean#sec-chp19-exercises), #14: Interpreting p-values for population mean.
:::

## Exercise 3

::: exercise
IMS - [Chapter 19 exercises](https://openintro-ims2.netlify.app/19-inference-one-mean#sec-chp19-exercises), #20: Possible bootstrap samples.
:::

## Exercise 4

::: exercise
IMS - [Chapter 20 exercises](https://openintro-ims2.netlify.app/20-inference-two-means#sec-chp20-exercises), #4: Lizards running, randomization test.
:::

## Exercise 5

::: exercise
IMS - [Chapter 20 exercises](https://openintro-ims2.netlify.app/20-inference-two-means#sec-chp20-exercises), #6: Lizards running, bootstrap interval.
:::

## Exercise 6

::: exercise
IMS - [Chapter 20 exercises](https://openintro-ims2.netlify.app/20-inference-two-means#sec-chp20-exercises), #10: A/B testing.
:::

## Exercise 7

::: exercise
IMS - [Chapter 21 exercises](https://openintro-ims2.netlify.app/21-inference-paired-means#sec-chp21-exercises), #6: High School and Beyond, randomization test.
:::
