---
title: Model selection
subtitle: Lecture 8
format: revealjs
auto-stretch: false
---

# Warm up

## Check-in

-   Daily check-ins for getting you thinking at the beginning of the class and reviewing recent/important concepts
-   Go to Canvas and open today's "quiz" titled `2023-09-27 Check-in`
-   Access code: `___` (released in class) <!-- parsimonious -->
-   "Graded" for completion

## Announcements {.smaller}

-   My remaining office hours this week:
    -   Wednesday 5-6 on Zoom (link emailed)
-   Project 1 teams + assignment to be posted later today
    -   Read before lab
    -   Sit with your teams in lab

# $R^2$ and adjusted $R^2$

## Two $R^2$s

-   $R^2$ measures the proportion of variability in the outcome variable that is explained by the model.

    -   Always goes up with the addition of a predictor.

-   Adjusted $R^2$ is this value adjusted to penalize for the number of predictors in the model.

    -   Goes up if the added predictor is "useful", i.e. actually increases the predictive performance of the model.

    -   Therefore we use this metric for choosing between models.

## Application exercise

Go to Posit Cloud and start the project titled ae-08-Tips.

::: callout-note
## ICYMI

Today's daily check-in access code: `___` (released in class)
:::
