---
title: Inference for two-way tables
subtitle: Lecture 18
format: revealjs
auto-stretch: false
---

# Warm up

## Announcements

-   Project 2: Video presentations, no in person meeting on Thu, Dec 14
-   Exam 2:
    -   Yes, you can have a cheat sheet
    -   Minor update in coverage: Up to end of inference with proportions, inference with means to start after exam

# Inference for two proportions

## NC poll on equality

A September 16-19, 2023, asked North Carolina voters, among other issues, about issues of equality and women's progress. Specifically, one of the questions asked:

> Which of these two statements come closest to your own views---even if neither is exactly right?
>
> -   The country has made most of the changes needed to give women equal rights with men.
>
> -   The country needs to continue to make changes to give women equal rights to men.

## Application exercise

::: task
Go to Posit Cloud and continue the project titled `ae-13 - Equality`.
:::

# Inference for two-way proportions

First:

::: task
Vote on Canvas under `2023-11-08 Check-in` with the access code `___`.
:::

. . .

Then:

::: task
Go to Posit Cloud and continue the project titled `ae-14 - Candidate talk`.
:::
