{
  "hash": "053acb9103e07803b157e1ed07080860",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Hypothesis testing with randomization\nsubtitle: Lecture 13\nformat: revealjs\nauto-stretch: false\n---\n\n\n# Warm up\n\n## Announcements\n\n-   Guest lecture on Wednesday with [Dr. Yue Jiang](http://www.yue-jiang.com/) -- make sure to do the reading before class!\n\n-   Shopping carts for Spring 2024 open today. If interested in more StatSci courses, I shared info on advising sessions on #random on course Slack.\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\n```\n:::\n\n\n# From last time...\n\n# Case study 1: Donors\n\n## Application exercise\n\nGo to Posit Cloud and continue the project titled `ae-10-Donor Yawner`.\n\n# Case study 2: Yawners\n\n## Is yawning contagious?\n\n::: task\nDo you think yawning is contagious?\n:::\n\n::: columns\n::: {.column width=\"50%\"}\n![](images/yawn1.png){fig-alt=\"Only Charlie Brown yawning\" fig-align=\"center\"}\n:::\n\n::: {.column width=\"50%\"}\n![](images/yawn2.png){fig-alt=\"Both Charlie Brown and Lucy van Pelt yawning\" fig-align=\"center\"}\n:::\n:::\n\n## Is yawning contagious?\n\nAn experiment conducted by the [MythBusters](https://en.wikipedia.org/wiki/MythBusters) tested if a person can be subconsciously influenced into yawning if another person near them yawns.\n\nIf you're interested, you can watch the full episode at <https://www.dailymotion.com/video/x7ydkt2>.\n\n## Study description\n\nIn this study 50 people were randomly assigned to two groups: 34 to a group where a person near them yawned (treatment) and 16 to a control group where they didn't see someone yawn (control).\n\nThe data are in the **openintro** package: `yawn`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyawn |>\n  count(group, result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  group result       n\n  <fct> <fct>    <int>\n1 ctrl  not yawn    12\n2 ctrl  yawn         4\n3 trmt  not yawn    24\n4 trmt  yawn        10\n```\n\n\n:::\n:::\n\n\n## Proportion of yawners\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nyawn |>\n  count(group, result) |>\n  group_by(group) |>\n  mutate(p_hat = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   group [2]\n  group result       n p_hat\n  <fct> <fct>    <int> <dbl>\n1 ctrl  not yawn    12 0.75 \n2 ctrl  yawn         4 0.25 \n3 trmt  not yawn    24 0.706\n4 trmt  yawn        10 0.294\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   Proportion of yawners in the treatment group: $\\frac{10}{34} = 0.2941$\n-   Proportion of yawners in the control group: $\\frac{4}{16} = 0.25$\n-   Difference: $0.2941 - 0.25 = 0.0441$\n-   Our results match the ones calculated on the MythBusters episode.\n\n## Independence?\n\n::: task\nBased on the proportions we calculated, do you think yawning is really contagious, i.e. are seeing someone yawn and yawning dependent?\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   group [2]\n  group result       n p_hat\n  <fct> <fct>    <int> <dbl>\n1 ctrl  not yawn    12 0.75 \n2 ctrl  yawn         4 0.25 \n3 trmt  not yawn    24 0.706\n4 trmt  yawn        10 0.294\n```\n\n\n:::\n:::\n\n\n## Dependence, or another possible explanation?\n\n::: incremental\n-   The observed differences might suggest that yawning is contagious, i.e. seeing someone yawn and yawning are dependent.\n-   But the differences are small enough that we might wonder if they might simple be **due to chance**.\n-   Perhaps if we were to repeat the experiment, we would see slightly different results.\n-   So we will do just that - well, somewhat - and see what happens.\n-   Instead of actually conducting the experiment many times, we will **simulate** our results.\n:::\n\n## Two competing claims\n\n::: columns\n::: {.column width=\"50%\"}\n**Null hypothesis:**\n\n\"There is nothing going on.\" Yawning and seeing someone yawn are **independent**, yawning is not contagious, observed difference in proportions is simply due to chance.\n:::\n\n::: {.column width=\"50%\"}\n**Alternative hypothesis:**\n\n\"There is something going on.\" Yawning and seeing someone yawn are **dependent**, yawning is contagious, observed difference in proportions is not due to chance.\n:::\n:::\n\n## Simulation by hand - setup\n\n1.  A regular deck of cards is comprised of 52 cards: 4 aces, 4 of numbers 2-10, 4 jacks, 4 queens, and 4 kings.\n\n2.  Take out two aces from the deck of cards and set them aside.\n\n3.  The remaining 50 playing cards to represent each participant in the study:\n\n    -   14 face cards (including the 2 aces) represent the people who yawn.\n    -   36 non-face cards represent the people who don't yawn.\n\n## Simulation by hand - running\n\n1.  Shuffle the 50 cards at least 7 times<sup>1</sup> to ensure that the cards counted out are from a random process.\n\n2.  Count out the top 16 cards and set them aside. These cards represent the people in the control group.\n\n3.  Out of the remaining 34 cards (treatment group) count the **number of face cards** (the number of people who yawned in the treatment group).\n\n4.  Calculate the difference in proportions of yawners (treatment - control), and record that value.\n\n5. Repeat steps 1-4 many times (100, 1000, 15000, ...) to build the null distribution of differences in proportions of yawners.\n\n::: aside\n\\[1\\] http://www.dartmouth.edu/\\~chance/course/topics/winning_number.html\n:::\n\n## Simulation by computation\n\nGo to Posit Cloud and continue the project titled `ae-10-Donor Yawner`.\n\n# Recap\n\n## Types of alternative hypotheses {.smaller}\n\n-   One-sided (one-tailed) alternatives: The parameter is hypothesized to be less than or greater than the null value, \\< or \\>\n\n. . .\n\n-   Two-sided (two-tailed) alternatives: The parameter is hypothesized to be not equal to the null value, $\\ne$\n    -   Calculated as two times the tail area beyond the observed sample statistic\n    -   More objective, and hence more widely preferred\n\n. . .\n\n::: task\nAverage systolic blood pressure of people with Stage 1 Hypertension is 150 mm Hg. Suppose we want to use a hypothesis test to evaluate whether a new blood pressure medication has <b>an effect</b> on the average blood pressure of heart patients. What are the hypotheses?\n:::\n\n## Discernability level\n\nWe often use 5% as the cutoff for whether the p-value is low enough that the data are unlikely to have come from the null model. This cutoff value is called the **discernability level**, $\\alpha$.\n\n-   If p-value \\< $\\alpha$, reject $H_0$ in favor of $H_A$: The data provide convincing evidence for the alternative hypothesis.\n\n-   If p-value \\> $\\alpha$, fail to reject $H_0$ in favor of $H_A$: The data do not provide convincing evidence for the alternative hypothesis.\n\n## Statistically discernable\n\n-   If you've taken a statistics course before, or read papers that use hypothesis testing for making a conclusion, you might have encountered the term \"statistically significant\" or \"significance level\".\n\n-   We will use the term \"statistically discernable\" or discernability level\", because \"significant\" has a different meaning in everyday language and this often causes misconceptions of what \"statistically significant\" means. It doesn't necessarily mean a notable or important event has happened, it just means the data are unlikely to have come from the null model.\n\n## Setting a seed\n\n-   Goal: Pin down the random generation so that the same random generation happens each time a document is rendered (by you or by someone else wanting to replicate your results)\n\n-   When: Set a seed each time right before `generate()`ing new resamples. Setting a seed once in a document would also work for re-rendering the document, but considering we often run the code chunk interactively, it's best to set the seed again in each code chunk that does random generation.\n\n# Confidence intervals\n\n## Case study 3: Airbnb in Asheville, NC\n\nWe have data on the price per guest (ppg) for a random sample of 50 Airbnb listings in 2020 for Asheville, NC. We are going to use these data to investigate what we would of expected to pay for an Airbnb in in Asheville, NC in June 2020.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabb <- read_csv(\"data/asheville.csv\")\n\nglimpse(abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 50\nColumns: 1\n$ ppg <dbl> 48.00000, 40.00000, 99.00000, 13.00000, 55.00000, 75.00000, 74.000…\n```\n\n\n:::\n:::\n\n\n## Terminology\n\n-   **Population parameter** - What we are interested in. Statistical measure that describes an entire population.\n\n-   **Sample statistic (point estimate)** - describes a sample. A piece of information you get from a fraction of the population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabb |> \n  summarize(ppg.mean = mean(ppg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  ppg.mean\n     <dbl>\n1     76.6\n```\n\n\n:::\n:::\n\n\n## Catching a fish\n\n::: task\nSuppose you're fishing in a murky lake. Are you more likely to catch a fish using a spear or a net?\n:::\n\n. . .\n\n- Spear $\\rightarrow$ point estimate\n- Net $\\rightarrow$ interval estimate\n\n## Constructing confidence intervals\n\nQuantifying the variability of the sample statistics to help calculate a range of plausible values for the population parameter of interest:\n\n- Via simulation $\\rightarrow$ using bootstrapping -- using a statistical procedure that re samples a single data set to create many simulated samples.\n\n- Via mathematical formulas $\\rightarrow$ using the Central Limit Theorem\n\n## Bootstrapping, what?\n\n- The term bootstrapping comes from the phrase \"pulling oneself up by one's bootstraps\", which is a metaphor for accomplishing an impossible task without any outside help.\n\n- Impossible task: estimating a population parameter using data from only the given sample.\n\n. . .\n\n::: callout-note\nNote: This notion of saying something about a population parameter using only information from an observed sample is the crux of statistical inference, it is not limited to bootstrapping.\n:::\n\n## Bootstrapping, how?\n\n- Resample with replacement from our data n times, where n is the sample size\n- Calculate the sample statistic of interest of the new, resampled (bootstrapped) sample and record the value\n- Do this entire process many many times to build the **bootstrap distribution**\n\n## Bootstrapping Airbnb rentals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(25) \n\nboot_dist_abb <- abb |>\n  specify(response = ppg) |>\n  generate(reps = 100, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n:::\n\n\n## The bootstrap distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(boot_dist_abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 2\n$ replicate <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ stat      <dbl> 73.11500, 78.78333, 80.19333, 83.42000, 70.15000, 73.03667, …\n```\n\n\n:::\n:::\n\n\n## Visualzing the bootstrap distribution\n\n::: task\nWhat do you expect the center of the bootstrap distribution to be? Why? Check your guess by visualizing the distribution.\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(boot_dist_abb, aes(x = stat)) + \n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](13-confidence-intervals-bootstrapping_files/figure-revealjs/boot-dist-abb-plot-1.png){width=576}\n:::\n:::\n\n\n## Calculating the bootstrap distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_dist_abb |>\n  summarize(\n    lower = quantile(stat, 0.025),\n    upper = quantile(stat, 0.975)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower upper\n  <dbl> <dbl>\n1  64.7  89.6\n```\n\n\n:::\n:::\n\n\n## Interpretation {.smaller}\n\n::: task\nWhich of the following is the correct interpretation of the bootstrap interval?\n\nReply on Canvas in \"2023-10-23 Check-in\" with access code `___`.\n:::\n\na. There is a 95% probability the true mean price per night for an Airbnb in Asheville is between $64.7 and $89.6.\n\nb. There is a 95% probability the price per night for an Airbnb in Asheville is between $64.7 and $89.6.\n\nc. We are 95% confident the true mean price per night for Airbnbs in Asheville is between $64.7 and $89.6.\n\nd. We are 95% confident the price per night for an Airbnb in Asheville is between $64.7 and $89.6.\n\n## Leveraging tidymodels tools further\n\nCalculating the observed sample statistic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_stat_abb <- abb |>\n  specify(response = ppg) |>\n  calculate(stat = \"mean\")  \n```\n:::\n\n\n## Leveraging tidymodels tools further\n\nCalculating the interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_95_abb <- boot_dist_abb |>\n  get_confidence_interval(\n    point_estimate = obs_stat_abb, \n    level = 0.95\n  )\n```\n:::\n\n\n## Leveraging tidymodels tools further\n\nVisualizing the interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(boot_dist_abb) +\n  shade_confidence_interval(ci_95_abb)\n```\n\n::: {.cell-output-display}\n![](13-confidence-intervals-bootstrapping_files/figure-revealjs/ci-95-abb-viz-1.png){width=576}\n:::\n:::\n",
    "supporting": [
      "13-confidence-intervals-bootstrapping_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}